name: flutter_processing
description: A Flutter version of Processing.
version: 0.1.1
homepage: https://github.com/matthew-carroll/flutter_processing

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  fast_noise: ^1.0.1
  image: ^3.0.2
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  golden_toolkit: ^0.9.0

flutter:
