name: Test project in a PR
on: [pull_request]
jobs:
  test_mac:
    runs-on: macos-latest
    steps:
      # Checkout the PR branch
      - uses: actions/checkout@v2
      # Setup Flutter environment
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      # Download all the packages that the app uses
      - run: flutter pub get
      # Run all tests
      - run: flutter test
